import "./globals.css";

import { Inter } from "next/font/google";
import Navbar from "@/app/components/navbar";
import CustomFooter from "@/app/components/CustomFooter";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "StayGlobal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`inter.className bg-white`}>
        <Navbar className="sticky top-0 px-1 md:px-10 h-16 z-50 bg-white" />
        <div className="px-1 md:px-10 w-full h-12 bg-stone-100 flex items-center justify-start font-light">
          RETURN POLICY
        </div>
        <div className="">
          {children}
          <CustomFooter className="px-1 md:px-10" />
        </div>
      </body>
    </html>
  );
}
